<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <PublishAot>true</PublishAot>
        <IlcScanReflection>false</IlcScanReflection>
        <StackTraceSupport>false</StackTraceSupport>
        <UseSystemResourceKeys>true</UseSystemResourceKeys>
        <OptimizationPreference>Size</OptimizationPreference>
        <InvariantGlobalization>true</InvariantGlobalization>
        <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\External\Hexa.NET.GLFW\Hexa.NET.GLFW.csproj"/>
        <ProjectReference Include="..\Vertex.NET.Impeller\Vertex.NET.Impeller.csproj"/>
    </ItemGroup>
</Project>
